version: '3.3'

services:
  app:
    image: kenuey/ad-platforms-testwork:latest
    ports:
      - "777:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6479:6379"
    command: ["redis-server", "--enable-debug-command", "yes"]
