version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "777:777"
    image: kenuey/ad-platforms-testwork:latest

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-server
